{
 "title": "VITAM standard dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Datasource", "label": "datasource", "query": "prometheus" },
   { "name": "proj", "query": "${VAR_PROJ}" },
   { "name": "server0", "label": "acc", "query": "${VAR_SERVER0}" },
   { "name": "server1", "label": "server1", "query": "${VAR_SERVER1}" },
   { "name": "server2", "label": "server2", "query": "${VAR_SERVER2}" },
   { "name": "server3", "label": "server3", "query": "${VAR_SERVER3}" },
   { "name": "server4", "label": "server4", "query": "${VAR_SERVER4}" },
   { "name": "server5", "label": "server5", "query": "${VAR_SERVER5}" }
  ]
 },
 "panels": [
  {
   "title": "Alert $proj",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "severity!=\\\"1\\\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Memory Warn",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "alertname=\"MemoryUsage\",severity=\"warning\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "CPU Load warn",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "alertname=\"high_cpu_load\",severity=\"warning\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Init workflow counter rate and current workflow total rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(Running_workflows{job=\"vitam-processing\"}[5m])",
     "legendFormat": "Init created workflow"
    },
    {
     "expr": "sum by(workflow) (rate(vitam_processing_workflow_operation_total{job=\"vitam-processing\"}[5m]))",
     "legendFormat": "Total operations per workflow{ workflow: {{workflow}} }"
    }
   ]
  },
  {
   "title": "Memory Crit",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "alertname=\"MemoryUsage\",severity=\"critical\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "CPU Load crit",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "alertname=\"high_cpu_load\",severity=\"critical\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "severity!=\"1\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "table"
    }
   ]
  },
  {
   "title": "Rate of completed workflows ( not ko )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(workflow) (rate(vitam_processing_workflow_operation_total{state=\"COMPLETED\",status!=\"KO\"}[5m]))",
     "legendFormat": "Total operations rate { workflow:{{workflow}} }"
    }
   ]
  },
  {
   "title": "Paused ingests",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "vitam_processing_workflow_operation_total{state=\"PAUSE\",workflow=\"INGEST\"}"
    }
   ]
  },
  {
   "title": "Started ingests",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "vitam_processing_workflow_operation_total{status=\"STARTED\",workflow=\"INGEST\"}"
    }
   ]
  },
  {
   "title": "Running ingests",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "vitam_processing_workflow_operation_total{state=\"RUNNING\",status=\"OK\",workflow=\"INGEST\"}"
    }
   ]
  },
  {
   "title": "Workers",
   "type": "stat",
   "description": "Number of registred workers",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "vitam_processing_worker_registered_total",
     "legendFormat": "Total of regisetred workers"
    }
   ]
  },
  {
   "title": "Rate of 5 minutes of write data in the offer in Kilo Bytes per tenant and strategy",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(tenant, strategy) (rate(vitam_requests_size_bytes_sum{job=\"vitam-storage-offer-default\"}[5m]) /rate(vitam_requests_size_bytes_count{job=\"vitam-storage-offer-default\"}[5m])) / 1024"
    }
   ]
  },
  {
   "title": "Completed workflow KO",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (workflow) (vitam_processing_workflow_operation_total{state=\"COMPLETED\",status=\"KO\"})",
     "legendFormat": "Total per workflow {workflow: {{workflow}}}"
    },
    {
     "expr": "rate(vitam_processing_workflow_operation_total{state=\"COMPLETED\",status=\"KO\"}[5m])*100",
     "legendFormat": "Rate of KO on 5 m."
    }
   ]
  },
  {
   "title": "Rate 5 minutes of read data from the offer in Kilo Bytes per tenant and strategy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(tenant, strategy) (rate(vitam_responses_size_bytes_sum{job=\"vitam-storage-offer-default\"}[5m]) /rate(vitam_responses_size_bytes_count{job=\"vitam-storage-offer-default\"}[5m])) / 1024"
    }
   ]
  },
  {
   "title": "Average over time (24h) traceability",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time (vitam_processing_workflow_operation_total{workflow=\"TRACEABILITY\", status=~\"OK|WARNING\"}[24h])",
     "legendFormat": "status: {{status}} state: {{state}}"
    }
   ]
  },
  {
   "title": "ACC server",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server0.*\"}",
     "legendFormat": "Load"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$server0.*\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$server0.*\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$server0.*\"}) by (cpu))",
     "legendFormat": "CPU Load"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$server0.*\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$server0.*\"})",
     "legendFormat": "Mem %"
    }
   ]
  },
  {
   "title": "APP server",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server1.*\"}",
     "legendFormat": "Load"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$server1.*\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$server1.*\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$server1.*\"}) by (cpu))",
     "legendFormat": "CPU Load"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$server1.*\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$server1.*\"})",
     "legendFormat": "Mem %"
    }
   ]
  },
  {
   "title": "Total operations in state PAUSE status FATAL or UNKNOWN",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(workflow) (vitam_processing_workflow_operation_total{state=\"PAUSE\", status=\"FATAL\"})",
     "legendFormat": "vitam_workflow_operation_total{status={{status}}}"
    },
    {
     "expr": "sum without(workflow) (vitam_processing_workflow_operation_total{state=\"PAUSE\", status=\"UNKNOWN\"})",
     "legendFormat": "vitam_workflow_operation_total{status={{status}}}"
    }
   ]
  },
  {
   "title": "DAT 1 server (elk)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server2.*\"}",
     "legendFormat": "Load"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$server2.*\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$server2.*\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$server2.*\"}) by (cpu))",
     "legendFormat": "CPU Load"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$server2.*\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$server2.*\"})",
     "legendFormat": "Mem %"
    }
   ]
  },
  {
   "title": "DAT 2 server (mongo)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server3.*\"}",
     "legendFormat": "Load"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$server3.*\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$server3.*\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$server3.*\"}) by (cpu))",
     "legendFormat": "CPU Load"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$server3.*\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$server3.*\"})",
     "legendFormat": "Mem %"
    }
   ]
  },
  {
   "title": "STO1 server",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server4.*\"}",
     "legendFormat": "Load"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$server4.*\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$server4.*\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$server4.*\"}) by (cpu))",
     "legendFormat": "CPU Load"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$server4.*\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$server4.*\"})",
     "legendFormat": "Mem %"
    }
   ]
  },
  {
   "title": "STO2 server",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server5.*\"}",
     "legendFormat": "Load"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$server5.*\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$server5.*\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$server5.*\"}) by (cpu))",
     "legendFormat": "CPU Load"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$server5.*\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$server5.*\"})",
     "legendFormat": "Mem %"
    }
   ]
  },
  {
   "title": "Disk space available $server3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=~\"$server4.*\",device!~'rootfs',device!~'tmpfs'}"
    }
   ]
  },
  {
   "title": "Disk space available $server4",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=~\"$server5.*\",device!~'rootfs',device!~'tmpfs'}"
    }
   ]
  },
  {
   "title": "Ingest step execution duration mean",
   "type": "bargauge",
   "description": "Le temps d'execution de chaque step du workflow INGEST",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(vitam_processing_workflow_step_execution_duration_seconds_sum{workflow=\"INGEST\"}[5m]) / rate(vitam_processing_workflow_step_execution_duration_seconds_count{workflow=\"INGEST\"}[5m])",
     "legendFormat": "{{workflow}}:{{step_name}}"
    }
   ]
  },
  {
   "title": "Load 1 - All servers",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=~\".*\"\r}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Temps moyens d'appels (Ingest) entre le distributeur et les workers par worker et par step",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short", "label": "Temps moyen" }
   ],
   "targets": [
    {
     "expr": "rate(vitam_worker_task_execution_duration_seconds_sum{instance=~\".*$proj.*\"\r, workflow=\"ingest\"}[5m]) / rate(vitam_worker_task_execution_duration_seconds_count{instance=~\".*$proj.*\"\r,workflow=\"ingest\"}[5m])",
     "legendFormat": "{{worker_name}}>{{step_name}}"
    }
   ]
  },
  {
   "title": "Consul - Services Health",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(status)(consul_health_service_status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Consul - Nodes Health",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(status)(consul_health_node_status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Consul - Services passed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(consul_health_service_status{status=\"passing\"} == 1)"
    }
   ]
  },
  {
   "title": "Temps moyens d'attente des tâches d'ingest dans la queue dans le distributeur",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "Temps moyen" }
   ],
   "targets": [
    {
     "expr": "rate(vitam_worker_task_idle_duration_in_queue_seconds_sum{instance=~\".*$proj.*\"\r, workflow=\"ingest\"}[5m]) / rate(vitam_worker_task_idle_duration_in_queue_seconds_count{instance=~\".*$proj.*\"\r, workflow=\"ingest\"}[5m])",
     "legendFormat": "{{worker_family}}:{{step_name}}"
    }
   ]
  },
  {
   "title": "Consul - Services critical",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(consul_health_service_status{status=\"critical\"} == 1)"
    }
   ]
  },
  {
   "title": "Consul Lan serf",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 52 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "consul_serf_lan_members" }
   ]
  },
  {
   "title": "PUT:application_octet_stream",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(_offer_v1__objects__type___objectId:___:PUT:application_octet_stream:application_json:timer{instance=~\".*$proj.*\"\r, job=~\".*$proj-offers\",quantile=\"0.999\"}[5m]) * 1024"
    }
   ]
  },
  {
   "title": "Total worker tasks in queue rate 5m",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vitam_worker_task_in_queue_total{instance=~\".*$proj.*\"\r}[5m])",
     "legendFormat": "rate 5m task in queue{ worker_family: {{worker_family}}}"
    }
   ]
  },
  {
   "title": "Workflow KO et Pause Fatal",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "vitam_workflow_operation_total{instance=~\".*$proj.*\", state=\"completed\",status=\"ko\",workflow=\"ingest\"}",
     "legendFormat": "INGEST completed KO"
    },
    {
     "expr": "vitam_workflow_operation_total{instance=~\".*$proj.*\",state=\"completed\",status=\"ko\",workflow=\"mass_update\"}",
     "legendFormat": "MASS_UPDATE completed KO"
    },
    {
     "expr": "vitam_workflow_operation_total{instance=~\".*$proj.*\",state=\"pause\",status=\"fatal\",workflow=\"ingest\"}",
     "legendFormat": "INGEST pause FATAL"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 10, "x": 13, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\".*\"\r} * 100) / node_memory_MemTotal_bytes{instance=~\".*\"\r})",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}